services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5050:5000"
    volumes:
      - ./backend:/app/backend:ro
      - ./Exercice_files:/app/Exercice_files
      - ./ide_projects:/app/ide_projects
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/app/backend/app.py
      - PROJECTS_DIR=/app/ide_projects
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=Userdatabase
    depends_on:
      - mongodb
    privileged: true
    user: "root"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  db_initializer:
    build:
      context: .
      dockerfile: Dockerfile.db_initializer
    container_name: db_initializer
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    command: ["python", "initialize_db.py"]

volumes:
  mongodb_data:
