version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend:ro
      - ./ide_projects:/app/ide_projects
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/app/backend/app.py
      - PROJECTS_DIR=/app/ide_projects
      - MONGO_URI=mongodb://mongodb:27017
      - MONGO_DB_NAME=my_database
    depends_on:
      - mongodb
    privileged: true
    user: "root"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
