version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend:ro
      - ./ide_projects:/app/ide_projects
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - FLASK_ENV=development
      - FLASK_APP=/app/backend/app.py
      - PROJECTS_DIR=/app/ide_projects
    privileged: true
    user: "root"  